version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 55008:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=stack-overflow-db
